var group__PTF__attributes =
[
    [ "callCnt", "group__httpwwwpurlorgogitPTFcallCnt.html", null ],
    [ "clientCnt", "group__httpwwwpurlorgogitPTFclientCnt.html", null ],
    [ "dbAwsMachineCnt", "group__httpwwwpurlorgogitPTFdbAwsMachineCnt.html", null ],
    [ "dbAwsMachineType", "group__httpwwwpurlorgogitPTFdbAwsMachineType.html", null ],
    [ "duration", "group__httpwwwpurlorgogitPTFduration.html", null ],
    [ "endTime", "group__httpwwwpurlorgogitPTFendTime.html", null ],
    [ "engineAwsMachineCnt", "group__httpwwwpurlorgogitPTFengineAwsMachineCnt.html", null ],
    [ "engineAwsMachineType", "group__httpwwwpurlorgogitPTFengineAwsMachineType.html", null ],
    [ "graphAwsMachineCnt", "group__httpwwwpurlorgogitPTFgraphAwsMachineCnt.html", null ],
    [ "graphAwsMachineType", "group__httpwwwpurlorgogitPTFgraphAwsMachineType.html", null ],
    [ "graphNodesCnt", "group__httpwwwpurlorgogitPTFgraphNodesCnt.html", null ],
    [ "hiroVsn", "group__httpwwwpurlorgogitPTFhiroVsn.html", null ],
    [ "hotTest", "group__httpwwwpurlorgogitPTFhotTest.html", null ],
    [ "iamAwsMachineCnt", "group__httpwwwpurlorgogitPTFiamAwsMachineCnt.html", null ],
    [ "iamAwsMachineType", "group__httpwwwpurlorgogitPTFiamAwsMachineType.html", null ],
    [ "issuesCnt", "group__httpwwwpurlorgogitPTFissuesCnt.html", null ],
    [ "kisCnt", "group__httpwwwpurlorgogitPTFkisCnt.html", null ],
    [ "linksCnt", "group__httpwwwpurlorgogitPTFlinksCnt.html", null ],
    [ "revProxyAwsMachineCnt", "group__httpwwwpurlorgogitPTFrevProxyAwsMachineCnt.html", null ],
    [ "revProxyAwsMachineType", "group__httpwwwpurlorgogitPTFrevProxyAwsMachineType.html", null ],
    [ "startTime", "group__httpwwwpurlorgogitPTFstartTime.html", null ],
    [ "vertexSearchCount", "group__httpwwwpurlorgogitPTFvertexSearchCount.html", null ],
    [ "vertexSearchFull", "group__httpwwwpurlorgogitPTFvertexSearchFull.html", null ]
];