var group__CustomerSupport____attributes =
[
    [ "allowAttachments", "group__httpwwwpurlorgogitCustomerSupportallowAttachments.html", null ],
    [ "customFieldNames", "group__httpwwwpurlorgogitCustomerSupportcustomFieldNames.html", null ],
    [ "defaultGroupId", "group__httpwwwpurlorgogitCustomerSupportdefaultGroupId.html", null ],
    [ "defaultOrganizationId", "group__httpwwwpurlorgogitCustomerSupportdefaultOrganizationId.html", null ],
    [ "deleted", "group__httpwwwpurlorgogitCustomerSupportdeleted.html", null ],
    [ "details", "group__httpwwwpurlorgogitCustomerSupportdetails.html", null ],
    [ "domainNames", "group__httpwwwpurlorgogitCustomerSupportdomainNames.html", null ],
    [ "hasIncidents", "group__httpwwwpurlorgogitCustomerSupporthasIncidents.html", null ],
    [ "htmlContent", "group__httpwwwpurlorgogitCustomerSupporthtmlContent.html", null ],
    [ "lastLoginAt", "group__httpwwwpurlorgogitCustomerSupportlastLoginAt.html", null ],
    [ "locale", "group__httpwwwpurlorgogitCustomerSupportlocale.html", null ],
    [ "metadata", "group__httpwwwpurlorgogitCustomerSupportmetadata.html", null ],
    [ "multiFactorAuth", "group__httpwwwpurlorgogitCustomerSupportmultiFactorAuth.html", null ],
    [ "note", "group__httpwwwpurlorgogitCustomerSupportnote.html", null ],
    [ "privateCommentsOnly", "group__httpwwwpurlorgogitCustomerSupportprivateCommentsOnly.html", null ],
    [ "public", "group__httpwwwpurlorgogitCustomerSupportpublic.html", null ],
    [ "recipient", "group__httpwwwpurlorgogitCustomerSupportrecipient.html", null ],
    [ "remoteId", "group__httpwwwpurlorgogitCustomerSupportremoteId.html", null ],
    [ "remoteType", "group__httpwwwpurlorgogitCustomerSupportremoteType.html", null ],
    [ "remoteUrl", "group__httpwwwpurlorgogitCustomerSupportremoteUrl.html", null ],
    [ "restrictedAgent", "group__httpwwwpurlorgogitCustomerSupportrestrictedAgent.html", null ],
    [ "role", "group__httpwwwpurlorgogitCustomerSupportrole.html", null ],
    [ "roleType", "group__httpwwwpurlorgogitCustomerSupportroleType.html", null ],
    [ "shareComments", "group__httpwwwpurlorgogitCustomerSupportshareComments.html", null ],
    [ "shareTickets", "group__httpwwwpurlorgogitCustomerSupportshareTickets.html", null ],
    [ "signature", "group__httpwwwpurlorgogitCustomerSupportsignature.html", null ],
    [ "suspended", "group__httpwwwpurlorgogitCustomerSupportsuspended.html", null ],
    [ "tags", "group__httpwwwpurlorgogitCustomerSupporttags.html", null ],
    [ "ticketRestriction", "group__httpwwwpurlorgogitCustomerSupportticketRestriction.html", null ],
    [ "timeZone", "group__httpwwwpurlorgogitCustomerSupporttimeZone.html", null ],
    [ "verified", "group__httpwwwpurlorgogitCustomerSupportverified.html", null ]
];