var group__BusinessProcess__entities =
[
    [ "BusinessProcess", "group__httpwwwpurlorgogitBusinessProcessBusinessProcess.html", null ],
    [ "BusinessRuleTask", "group__httpwwwpurlorgogitBusinessProcessBusinessRuleTask.html", null ],
    [ "CancelEvent", "group__httpwwwpurlorgogitBusinessProcessCancelEvent.html", null ],
    [ "CompensationEvent", "group__httpwwwpurlorgogitBusinessProcessCompensationEvent.html", null ],
    [ "ConditionalEvent", "group__httpwwwpurlorgogitBusinessProcessConditionalEvent.html", null ],
    [ "DataObject", "group__httpwwwpurlorgogitBusinessProcessDataObject.html", null ],
    [ "DataStore", "group__httpwwwpurlorgogitBusinessProcessDataStore.html", null ],
    [ "ErrorEvent", "group__httpwwwpurlorgogitBusinessProcessErrorEvent.html", null ],
    [ "EscalationEvent", "group__httpwwwpurlorgogitBusinessProcessEscalationEvent.html", null ],
    [ "EventBasedGateway", "group__httpwwwpurlorgogitBusinessProcessEventBasedGateway.html", null ],
    [ "ExclusiveGateway", "group__httpwwwpurlorgogitBusinessProcessExclusiveGateway.html", null ],
    [ "InclusiveGateway", "group__httpwwwpurlorgogitBusinessProcessInclusiveGateway.html", null ],
    [ "InstantiatedReceiveTask", "group__httpwwwpurlorgogitBusinessProcessInstantiatedReceiveTask.html", null ],
    [ "LinkEvent", "group__httpwwwpurlorgogitBusinessProcessLinkEvent.html", null ],
    [ "ManualTask", "group__httpwwwpurlorgogitBusinessProcessManualTask.html", null ],
    [ "MessageEvent", "group__httpwwwpurlorgogitBusinessProcessMessageEvent.html", null ],
    [ "Milestone", "group__httpwwwpurlorgogitBusinessProcessMilestone.html", null ],
    [ "MultipleEvent", "group__httpwwwpurlorgogitBusinessProcessMultipleEvent.html", null ],
    [ "NoneEvent", "group__httpwwwpurlorgogitBusinessProcessNoneEvent.html", null ],
    [ "ParallelGateway", "group__httpwwwpurlorgogitBusinessProcessParallelGateway.html", null ],
    [ "ProcessLane", "group__httpwwwpurlorgogitBusinessProcessProcessLane.html", null ],
    [ "ProcessPool", "group__httpwwwpurlorgogitBusinessProcessProcessPool.html", null ],
    [ "Project", "group__httpwwwpurlorgogitBusinessProcessProject.html", null ],
    [ "ReceiveTask", "group__httpwwwpurlorgogitBusinessProcessReceiveTask.html", null ],
    [ "ScriptTask", "group__httpwwwpurlorgogitBusinessProcessScriptTask.html", null ],
    [ "SendTask", "group__httpwwwpurlorgogitBusinessProcessSendTask.html", null ],
    [ "ServiceTask", "group__httpwwwpurlorgogitBusinessProcessServiceTask.html", null ],
    [ "SignalEvent", "group__httpwwwpurlorgogitBusinessProcessSignalEvent.html", null ],
    [ "Survey", "group__httpwwwpurlorgogitBusinessProcessSurvey.html", null ],
    [ "SurveyIteration", "group__httpwwwpurlorgogitBusinessProcessSurveyIteration.html", null ],
    [ "SurveyReply", "group__httpwwwpurlorgogitBusinessProcessSurveyReply.html", null ],
    [ "TerminationEvent", "group__httpwwwpurlorgogitBusinessProcessTerminationEvent.html", null ],
    [ "TimerEvent", "group__httpwwwpurlorgogitBusinessProcessTimerEvent.html", null ],
    [ "UndefinedTask", "group__httpwwwpurlorgogitBusinessProcessUndefinedTask.html", null ],
    [ "UserTask", "group__httpwwwpurlorgogitBusinessProcessUserTask.html", null ]
];