var group__Forum__entities =
[
    [ "Award", "group__httpwwwpurlorgogitForumAward.html", null ],
    [ "Banner", "group__httpwwwpurlorgogitForumBanner.html", null ],
    [ "Configuration", "group__httpwwwpurlorgogitForumConfiguration.html", null ],
    [ "FeedEntry", "group__httpwwwpurlorgogitForumFeedEntry.html", null ],
    [ "Group", "group__httpwwwpurlorgogitForumGroup.html", null ],
    [ "Invite", "group__httpwwwpurlorgogitForumInvite.html", null ],
    [ "KnowledgeBundle", "group__httpwwwpurlorgogitForumKnowledgeBundle.html", null ],
    [ "KnowledgeBundleHistory", "group__httpwwwpurlorgogitForumKnowledgeBundleHistory.html", null ],
    [ "KnowledgeItemHistory", "group__httpwwwpurlorgogitForumKnowledgeItemHistory.html", null ],
    [ "Permission", "group__httpwwwpurlorgogitForumPermission.html", null ],
    [ "Post", "group__httpwwwpurlorgogitForumPost.html", null ],
    [ "Profile", "group__httpwwwpurlorgogitForumProfile.html", null ],
    [ "Rating", "group__httpwwwpurlorgogitForumRating.html", null ],
    [ "Reply", "group__httpwwwpurlorgogitForumReply.html", null ],
    [ "Review", "group__httpwwwpurlorgogitForumReview.html", null ],
    [ "Role", "group__httpwwwpurlorgogitForumRole.html", null ],
    [ "ShortId", "group__httpwwwpurlorgogitForumShortId.html", null ],
    [ "Tag", "group__httpwwwpurlorgogitForumTag.html", null ],
    [ "Topic", "group__httpwwwpurlorgogitForumTopic.html", null ],
    [ "Workflow", "group__httpwwwpurlorgogitForumWorkflow.html", null ],
    [ "WorkflowStep", "group__httpwwwpurlorgogitForumWorkflowStep.html", null ],
    [ "WorkflowTemplate", "group__httpwwwpurlorgogitForumWorkflowTemplate.html", null ]
];