var group__entitiesSGO =
[
    [ "ogit/Account", "group__httpwwwpurlorgogitAccount.html", null ],
    [ "ogit/Alert", "group__httpwwwpurlorgogitAlert.html", null ],
    [ "ogit/Asset", "group__httpwwwpurlorgogitAsset.html", null ],
    [ "ogit/Attachment", "group__httpwwwpurlorgogitAttachment.html", null ],
    [ "ogit/Catalog", "group__httpwwwpurlorgogitCatalog.html", null ],
    [ "ogit/CatalogItem", "group__httpwwwpurlorgogitCatalogItem.html", null ],
    [ "ogit/Comment", "group__httpwwwpurlorgogitComment.html", null ],
    [ "ogit/ConfigurationItem", "group__httpwwwpurlorgogitConfigurationItem.html", null ],
    [ "ogit/Contract", "group__httpwwwpurlorgogitContract.html", null ],
    [ "ogit/CustomApplicationData", "group__httpwwwpurlorgogitCustomApplicationData.html", null ],
    [ "ogit/Device", "group__httpwwwpurlorgogitDevice.html", null ],
    [ "ogit/Email", "group__httpwwwpurlorgogitEmail.html", null ],
    [ "ogit/Event", "group__httpwwwpurlorgogitEvent.html", null ],
    [ "ogit/Hyperlink", "group__httpwwwpurlorgogitHyperlink.html", null ],
    [ "ogit/License", "group__httpwwwpurlorgogitLicense.html", null ],
    [ "ogit/LicenseRequest", "group__httpwwwpurlorgogitLicenseRequest.html", null ],
    [ "ogit/LicenseToken", "group__httpwwwpurlorgogitLicenseToken.html", null ],
    [ "ogit/Location", "group__httpwwwpurlorgogitLocation.html", null ],
    [ "ogit/Note", "group__httpwwwpurlorgogitNote.html", null ],
    [ "ogit/Notification", "group__httpwwwpurlorgogitNotification.html", null ],
    [ "ogit/Organization", "group__httpwwwpurlorgogitOrganization.html", null ],
    [ "ogit/Parameter", "group__httpwwwpurlorgogitParameter.html", null ],
    [ "ogit/ParameterType", "group__httpwwwpurlorgogitParameterType.html", null ],
    [ "ogit/Penalty", "group__httpwwwpurlorgogitPenalty.html", null ],
    [ "ogit/Person", "group__httpwwwpurlorgogitPerson.html", null ],
    [ "ogit/Policy", "group__httpwwwpurlorgogitPolicy.html", null ],
    [ "ogit/Question", "group__httpwwwpurlorgogitQuestion.html", null ],
    [ "ogit/Region", "group__httpwwwpurlorgogitRegion.html", null ],
    [ "ogit/Role", "group__httpwwwpurlorgogitRole.html", null ],
    [ "ogit/Schema", "group__httpwwwpurlorgogitSchema.html", null ],
    [ "ogit/Task", "group__httpwwwpurlorgogitTask.html", null ],
    [ "ogit/TaskList", "group__httpwwwpurlorgogitTaskList.html", null ],
    [ "ogit/Timeseries", "group__httpwwwpurlorgogitTimeseries.html", null ],
    [ "ogit/Vcard", "group__httpwwwpurlorgogitVcard.html", null ]
];