var group__entitiesBusinessProcess =
[
    [ "ogit/BusinessProcess/BusinessProcess", "group__httpwwwpurlorgogitBusinessProcessBusinessProcess.html", null ],
    [ "ogit/BusinessProcess/BusinessRuleTask", "group__httpwwwpurlorgogitBusinessProcessBusinessRuleTask.html", null ],
    [ "ogit/BusinessProcess/CancelEvent", "group__httpwwwpurlorgogitBusinessProcessCancelEvent.html", null ],
    [ "ogit/BusinessProcess/CompensationEvent", "group__httpwwwpurlorgogitBusinessProcessCompensationEvent.html", null ],
    [ "ogit/BusinessProcess/ConditionalEvent", "group__httpwwwpurlorgogitBusinessProcessConditionalEvent.html", null ],
    [ "ogit/BusinessProcess/DataObject", "group__httpwwwpurlorgogitBusinessProcessDataObject.html", null ],
    [ "ogit/BusinessProcess/DataStore", "group__httpwwwpurlorgogitBusinessProcessDataStore.html", null ],
    [ "ogit/BusinessProcess/ErrorEvent", "group__httpwwwpurlorgogitBusinessProcessErrorEvent.html", null ],
    [ "ogit/BusinessProcess/EscalationEvent", "group__httpwwwpurlorgogitBusinessProcessEscalationEvent.html", null ],
    [ "ogit/BusinessProcess/EventBasedGateway", "group__httpwwwpurlorgogitBusinessProcessEventBasedGateway.html", null ],
    [ "ogit/BusinessProcess/ExclusiveGateway", "group__httpwwwpurlorgogitBusinessProcessExclusiveGateway.html", null ],
    [ "ogit/BusinessProcess/InclusiveGateway", "group__httpwwwpurlorgogitBusinessProcessInclusiveGateway.html", null ],
    [ "ogit/BusinessProcess/InstantiatedReceiveTask", "group__httpwwwpurlorgogitBusinessProcessInstantiatedReceiveTask.html", null ],
    [ "ogit/BusinessProcess/LinkEvent", "group__httpwwwpurlorgogitBusinessProcessLinkEvent.html", null ],
    [ "ogit/BusinessProcess/ManualTask", "group__httpwwwpurlorgogitBusinessProcessManualTask.html", null ],
    [ "ogit/BusinessProcess/MessageEvent", "group__httpwwwpurlorgogitBusinessProcessMessageEvent.html", null ],
    [ "ogit/BusinessProcess/Milestone", "group__httpwwwpurlorgogitBusinessProcessMilestone.html", null ],
    [ "ogit/BusinessProcess/MultipleEvent", "group__httpwwwpurlorgogitBusinessProcessMultipleEvent.html", null ],
    [ "ogit/BusinessProcess/NoneEvent", "group__httpwwwpurlorgogitBusinessProcessNoneEvent.html", null ],
    [ "ogit/BusinessProcess/ParallelGateway", "group__httpwwwpurlorgogitBusinessProcessParallelGateway.html", null ],
    [ "ogit/BusinessProcess/ProcessLane", "group__httpwwwpurlorgogitBusinessProcessProcessLane.html", null ],
    [ "ogit/BusinessProcess/ProcessPool", "group__httpwwwpurlorgogitBusinessProcessProcessPool.html", null ],
    [ "ogit/BusinessProcess/Project", "group__httpwwwpurlorgogitBusinessProcessProject.html", null ],
    [ "ogit/BusinessProcess/ReceiveTask", "group__httpwwwpurlorgogitBusinessProcessReceiveTask.html", null ],
    [ "ogit/BusinessProcess/ScriptTask", "group__httpwwwpurlorgogitBusinessProcessScriptTask.html", null ],
    [ "ogit/BusinessProcess/SendTask", "group__httpwwwpurlorgogitBusinessProcessSendTask.html", null ],
    [ "ogit/BusinessProcess/ServiceTask", "group__httpwwwpurlorgogitBusinessProcessServiceTask.html", null ],
    [ "ogit/BusinessProcess/SignalEvent", "group__httpwwwpurlorgogitBusinessProcessSignalEvent.html", null ],
    [ "ogit/BusinessProcess/Survey", "group__httpwwwpurlorgogitBusinessProcessSurvey.html", null ],
    [ "ogit/BusinessProcess/SurveyIteration", "group__httpwwwpurlorgogitBusinessProcessSurveyIteration.html", null ],
    [ "ogit/BusinessProcess/SurveyReply", "group__httpwwwpurlorgogitBusinessProcessSurveyReply.html", null ],
    [ "ogit/BusinessProcess/TerminationEvent", "group__httpwwwpurlorgogitBusinessProcessTerminationEvent.html", null ],
    [ "ogit/BusinessProcess/TimerEvent", "group__httpwwwpurlorgogitBusinessProcessTimerEvent.html", null ],
    [ "ogit/BusinessProcess/UndefinedTask", "group__httpwwwpurlorgogitBusinessProcessUndefinedTask.html", null ],
    [ "ogit/BusinessProcess/UserTask", "group__httpwwwpurlorgogitBusinessProcessUserTask.html", null ]
];