var group__entities =
[
    [ "Automation", "group__entitiesAutomation.html", "group__entitiesAutomation" ],
    [ "BusinessProcess", "group__entitiesBusinessProcess.html", "group__entitiesBusinessProcess" ],
    [ "Cost", "group__entitiesCost.html", "group__entitiesCost" ],
    [ "DataProcessing", "group__entitiesDataProcessing.html", "group__entitiesDataProcessing" ],
    [ "Datacenter", "group__entitiesDatacenter.html", "group__entitiesDatacenter" ],
    [ "Forum", "group__entitiesForum.html", "group__entitiesForum" ],
    [ "Network", "group__entitiesNetwork.html", "group__entitiesNetwork" ],
    [ "OSLC-arch", "group__entitiesOSLC-arch.html", "group__entitiesOSLC-arch" ],
    [ "OSLC-asset", "group__entitiesOSLC-asset.html", "group__entitiesOSLC-asset" ],
    [ "OSLC-automation", "group__entitiesOSLC-automation.html", "group__entitiesOSLC-automation" ],
    [ "OSLC-change", "group__entitiesOSLC-change.html", "group__entitiesOSLC-change" ],
    [ "OSLC-core", "group__entitiesOSLC-core.html", "group__entitiesOSLC-core" ],
    [ "OSLC-crtv", "group__entitiesOSLC-crtv.html", "group__entitiesOSLC-crtv" ],
    [ "OSLC-ems", "group__entitiesOSLC-ems.html", "group__entitiesOSLC-ems" ],
    [ "OSLC-perfmon", "group__entitiesOSLC-perfmon.html", "group__entitiesOSLC-perfmon" ],
    [ "OSLC-qm", "group__entitiesOSLC-qm.html", "group__entitiesOSLC-qm" ],
    [ "OSLC-reqman", "group__entitiesOSLC-reqman.html", "group__entitiesOSLC-reqman" ],
    [ "Price", "group__entitiesPrice.html", "group__entitiesPrice" ],
    [ "RDDL", "group__entitiesRDDL.html", "group__entitiesRDDL" ],
    [ "SGO", "group__entitiesSGO.html", "group__entitiesSGO" ],
    [ "ServiceManagement", "group__entitiesServiceManagement.html", "group__entitiesServiceManagement" ],
    [ "Software", "group__entitiesSoftware.html", "group__entitiesSoftware" ],
    [ "Statistics", "group__entitiesStatistics.html", "group__entitiesStatistics" ],
    [ "UserMeta", "group__entitiesUserMeta.html", "group__entitiesUserMeta" ]
];