var group__Mobile____attributes =
[
    [ "appPermissions", "group__httpwwwpurlorgogitMobileappPermissions.html", null ],
    [ "appVersion", "group__httpwwwpurlorgogitMobileappVersion.html", null ],
    [ "category", "group__httpwwwpurlorgogitMobilecategory.html", null ],
    [ "criticality", "group__httpwwwpurlorgogitMobilecriticality.html", null ],
    [ "cta", "group__httpwwwpurlorgogitMobilecta.html", null ],
    [ "ctaTarget", "group__httpwwwpurlorgogitMobilectaTarget.html", null ],
    [ "ctaType", "group__httpwwwpurlorgogitMobilectaType.html", null ],
    [ "delivered", "group__httpwwwpurlorgogitMobiledelivered.html", null ],
    [ "deviceType", "group__httpwwwpurlorgogitMobiledeviceType.html", null ],
    [ "distance", "group__httpwwwpurlorgogitMobiledistance.html", null ],
    [ "duration", "group__httpwwwpurlorgogitMobileduration.html", null ],
    [ "enctime", "group__httpwwwpurlorgogitMobileenctime.html", null ],
    [ "firebaseToken", "group__httpwwwpurlorgogitMobilefirebaseToken.html", null ],
    [ "headline", "group__httpwwwpurlorgogitMobileheadline.html", null ],
    [ "locale", "group__httpwwwpurlorgogitMobilelocale.html", null ],
    [ "message", "group__httpwwwpurlorgogitMobilemessage.html", null ],
    [ "movementType", "group__httpwwwpurlorgogitMobilemovementType.html", null ],
    [ "osVersion", "group__httpwwwpurlorgogitMobileosVersion.html", null ],
    [ "registrationType", "group__httpwwwpurlorgogitMobileregistrationType.html", null ],
    [ "riskScore", "group__httpwwwpurlorgogitMobileriskScore.html", null ],
    [ "subline", "group__httpwwwpurlorgogitMobilesubline.html", null ],
    [ "time", "group__httpwwwpurlorgogitMobiletime.html", null ],
    [ "uuid", "group__httpwwwpurlorgogitMobileuuid.html", null ]
];