var modules =
[
    [ "Auth", "group__Auth.html", null ],
    [ "AutoPilotIssue", "group__httpwwwpurlorgogitAutomationAutomationIssue.html", "group__httpwwwpurlorgogitAutomationAutomationIssue" ],
    [ "Cost", "group__Cost.html", null ],
    [ "Forum", "group__Forum.html", null ],
    [ "HR", "group__HR.html", null ],
    [ "MARS", "group__MARS.html", null ],
    [ "MRO", "group__MRO.html", null ],
    [ "MRP", "group__MRP.html", null ],
    [ "OSLC-arch", "group__OSLC-arch.html", null ],
    [ "OSLC-asset", "group__OSLC-asset.html", null ],
    [ "OSLC-automation", "group__OSLC-automation.html", null ],
    [ "OSLC-change", "group__OSLC-change.html", null ],
    [ "OSLC-core", "group__OSLC-core.html", null ],
    [ "OSLC-crtv", "group__OSLC-crtv.html", null ],
    [ "OSLC-ems", "group__OSLC-ems.html", null ],
    [ "OSLC-perfmon", "group__OSLC-perfmon.html", null ],
    [ "OSLC-qm", "group__OSLC-qm.html", null ],
    [ "OSLC-reqman", "group__OSLC-reqman.html", null ],
    [ "PTF", "group__PTF.html", null ],
    [ "RDDL", "group__RDDL.html", null ],
    [ "RPA", "group__RPA.html", null ],
    [ "Statistics", "group__Statistics.html", null ],
    [ "UserMeta", "group__UserMeta.html", null ],
    [ "Version", "group__Version.html", null ]
];