var modules =
[
    [ "Automation", "group__Automation.html", "group__Automation" ],
    [ "BusinessProcess", "group__BusinessProcess.html", "group__BusinessProcess" ],
    [ "Cost", "group__Cost.html", "group__Cost" ],
    [ "Data", "group__Data.html", "group__Data" ],
    [ "DataProcessing", "group__DataProcessing.html", "group__DataProcessing" ],
    [ "Datacenter", "group__Datacenter.html", "group__Datacenter" ],
    [ "Forum", "group__Forum.html", "group__Forum" ],
    [ "Knowledge", "group__Knowledge.html", "group__Knowledge" ],
    [ "Network", "group__Network.html", "group__Network" ],
    [ "OSLC-arch", "group__OSLC-arch.html", "group__OSLC-arch" ],
    [ "OSLC-asset", "group__OSLC-asset.html", "group__OSLC-asset" ],
    [ "OSLC-automation", "group__OSLC-automation.html", "group__OSLC-automation" ],
    [ "OSLC-change", "group__OSLC-change.html", "group__OSLC-change" ],
    [ "OSLC-core", "group__OSLC-core.html", "group__OSLC-core" ],
    [ "OSLC-crtv", "group__OSLC-crtv.html", "group__OSLC-crtv" ],
    [ "OSLC-ems", "group__OSLC-ems.html", "group__OSLC-ems" ],
    [ "OSLC-perfmon", "group__OSLC-perfmon.html", "group__OSLC-perfmon" ],
    [ "OSLC-qm", "group__OSLC-qm.html", "group__OSLC-qm" ],
    [ "OSLC-reqman", "group__OSLC-reqman.html", "group__OSLC-reqman" ],
    [ "Price", "group__Price.html", "group__Price" ],
    [ "Project", "group__Project.html", "group__Project" ],
    [ "RDDL", "group__RDDL.html", "group__RDDL" ],
    [ "SGO", "group__SGO.html", "group__SGO" ],
    [ "ServiceManagement", "group__ServiceManagement.html", "group__ServiceManagement" ],
    [ "Software", "group__Software.html", "group__Software" ],
    [ "Statistics", "group__Statistics.html", "group__Statistics" ],
    [ "Survey", "group__Survey.html", "group__Survey" ],
    [ "UserMeta", "group__UserMeta.html", "group__UserMeta" ]
];