- Attribute:
    id: "the id of the attribute"
    name: "name of the attribute"
    description: "description of the attribute"
    valid-from: "date from when this attribute is valid 2013-11-01 00:00:00"
    valid-until: "date until this attribute is valid 2014-11-01 00:00:00"
    creator: "id of the user who created this attribute"
    deleter: "id of the user who made this attribute obsolete"
    created:  "2013-09-01"
    modified: "2013-09-01"
    admin-contact: "id of user"
    tech-contact: "id of user"
    hide: "true or false, if true, then no html documantion will be create, default is 'false'"
    validation-type: "validation type"
    validation-parameter: "validation parameter"
    history:
      - id: 1
        date: "date of the change"
        description: "description of the change"
        modified-by: "id of the modifier"
